# .github/workflows/tests.yaml
name: Tests

on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
        stability: [ prefer-lowest, prefer-stable ]
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} tests
    
    steps:
      # basically git clone
      - uses: actions/checkout@v4

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop && sudo service mysql status

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      # use PHP of specific version
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mysql, pdo, pdo_mysql
          coverage: pcov
     # Install MySQL     
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
      - run: mysql -uroot -e 'SELECT version()'

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit --testdox