# .github/workflows/tests.yaml
name: Tests

on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3']
        stability: [ prefer-lowest, prefer-stable ]
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} tests
    steps:
      # basically git clone
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      # use PHP of specific version
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcov, pdo_mysql
          coverage: pcov
     # Install MySQL     
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: '' # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'user' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'user' # Required if "mysql user" exists. The password for the "mysql user"
      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit --testdox